### ISSUE TITLE
[BUG]Keka Extension in Big Sur(20B29), external hard drives icon is incorrect in Finder

### ISSUE THREAD

**Issue by zhouweiluan** [aonez/Keka#667]
### Configuration
- Keka version: 1.2.2 (4199)
- macOS version: 11.0.1 (20B29)

### Describe the bug
在macOS Big Sur 11.0.1 (20B29), 在打开了Keka的Finder扩展的情况下，Finder里外接磁盘的图标显示会不正确。
in macOS Big Sur 11.0.1 (20B29), If the Keka extension is enabled, the external hard drives icon is incorrect in Finder

### Screenshots
https://www.v2ex.com/i/c9nfK52y.png

**Comment by zhouweiluan** [comment]
append video
[屏幕录制2020-11-17 下午5.18.42.zip](https://github.com/aonez/Keka/files/5552416/2020-11-17.5.18.42.zip)

**Comment by aonez** [comment]
Thanks @zhouweiluan!

**Comment by gingerbeardman** [comment]
This is an Apple bug. Workaround is here: https://github.com/knurling/ServiceStation/issues/40#issuecomment-653660235

**Comment by aonez** [comment]
So seems that this should be fixed by Apple then... I can meanwhile add an option to disable external disk monitoring, so the Finder Extension will only be present at external disks that where mounted when the extension started.

**Comment by aonez** [comment]
This build has the option to disable the external volumes integration: [Keka-appx-volumes.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-appx-volumes.7z)

I've tested and this fixes the issue although renders the context menu useless outside the OS drive 😞

Hopefully Apple can fix this soon.

**Comment by aonez** [comment]
Version 1.2.3 is released now with the option to workaround this issue.

**Comment by pkamb** [comment]
Where did you get the information about "Big Sur 11.0.1 and earlier"?

I am reproducing this issue on Big Sur 11.1 Beta (20C5048l) on a DTK. I don't yet have access to a non-beta install.

I opened a ticket for it in my Finder Sync Extension here: https://github.com/knurling/ServiceStation/issues/51

**Comment by aonez** [comment]
I meant 11.0 and 11.0.1... Haven't had the change to try 11.1 beta yet. Just changed the descriptions there's no confusion. I've already posted in your previous issue https://github.com/knurling/ServiceStation/issues/40#issuecomment-728856509. Will be creating a feedback ticket for  pointing this issue and yours.

Sadly this error reminds me of https://github.com/aonez/Keka/issues/453, an error introduced in Catalina that was fixed in Big Sur... Hopefully they fix this one in Big Sur and not in macOS 12.0 or whatever they call the new one.

**Comment by lfom** [comment]
I still see the same problem with Keka v1.2.9 (4434) on Catalina 10.15.7: when "Show in external volumes" or the Finder extension is enabled, disks other than the internal boot one is shown as a generic folder icon.

![Screen Shot 2021-02-03 at 07 44 15](https://user-images.githubusercontent.com/15659999/106735974-a3882900-65f3-11eb-8ccc-1e23fb374553.png)

**Comment by gingerbeardman** [comment]
@lfom please read earlier comments

**Comment by aonez** [comment]
@lfom just disable external volumes in Keka - Preferences - Finder extension as stated in the main topic of this issue. Thanks!

**Comment by lfom** [comment]
Yeah, I know the workaround (as I wrote in my previous comment). Ibjust wanted to report that it also happens in Catalina. And also Mojave, by the way,  so it is no specific to BS.

**Comment by aonez** [comment]
Ah thanks @lfom! I did fund this in Catalina but did not tested Mojave.

**Comment by gingerbeardman** [comment]
I can confirm it happens in Mojave.

**Comment by l782993610** [comment]
Still happen on Big Sur 11.4 （Mac pro 2020 M1）

**Comment by SpyderZ** [comment]
Confirmed this happens on Big Sur and corrected it by turning off external volumes in settings.

**Comment by lexrus** [comment]
<img width="134" alt="1adf06a6-e79e-4ae5-9f64-0da6a05e6cd0-1" src="https://user-images.githubusercontent.com/219689/141394092-791219c9-654c-494d-9909-c1a522747b09.png">
I wonder how does Dropbox workaround this issue...

**Comment by aonez** [comment]
@lexrus Dropbox add an icon to its folder, as I remember. Keka does not add any icon to any folder but macOS renders bad icons to external drives.

**Comment by sbarex** [comment]
On my system the bug also occurs for the normal monitored folder visible in the sidebar.

**Comment by aonez** [comment]
@sbarex this will affect all directories (folders or volumes), other than this ones (from [Apple's doc](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Finder.html#//apple_ref/doc/uid/TP40014214-CH15)):


>NOTE
The sidebar icons you provide will replace the default folder icons in the Finder’s sidebar for any of the root folders that your extension is monitoring. This icon does not replace the icon for any folders contained by your monitored folder. It also does not replace the icon for any system folders that you may be monitoring (for example, Documents, Desktop, Applications, and Downloads).

So you can simply add parent folder to the Finder Extension list instead of the folder you're adding to the sidebar.

An example:

- Adding `/Users/sbarex/Documents/MySidebarFolder` to the sidebar
- Adding `/Users/sbarex/Documents/MySidebarFolder` to Keka's Finder Extension list
- `MySidebarFolder` has a bad icon

Workaround:

- Adding `/Users/sbarex/Documents/MySidebarFolder` to the sidebar
- Adding `/Users/sbarex/Documents` to Keka's Finder Extension list
- `MySidebarFolder` has the correct icon

**Comment by milketest** [comment]
@aonez, it seems you fixed this in the latest versions... I have the option to show Finder context menu items on external volumes set to ON and I see Keka related menu items on files on external volumes, but volumes icons in the sidebar stay undisturbed, like it is meant to be.

Would you mind sharing how you did it?
